dist: xenial
language: node_js
node_js:
- node
- lts/*
env:
  global:
    secure: LKaq8Xtil4kkJYBTWND9VzB1wEvY1yy7VRLlnqWrMzRCf0dzFRDeYjV9s69me/AsIljWsBqZqmX4pnBO5gZUZYCo+pOs5SQx8hKtE+ozTl/BKiCH4Ti7yG+6mr/jwxEQGDNzY2oNv4ExU6yf9BZf8c+0RguXOaJ5ikXTvd8f/2IAJ3czKrp+s6xANEV929GcA4jHVFvbqL1M36JQAS99m6NXto8PTzZtH7LGoI3RNfoScjE03S56SLx0u7Sf3Mq4gwZbcj+zT6QssZgTTfrkWabx4JZImsc+1r3aEs82CDIXd5EuozHsaKxkXytqLisZ48fKVgaqm+GES0DGwLrtQeGTXLEVn1TxjK9tzjn5nN9EDb4NCdjdPdxQJeMUk36Mbir3/nMQEPaiLSZ8QWj91/RXzMPy9U33+TWi7rDY8SgQZxdoO1fgVV8oxDevoP0qjiFK1d44SOOcm3TdasLMLUKt/0tbaFoCLRhIuIH/Hd2Auxf5mwDfN7MENUQXDwo/eMYIOiTHjdkqIHt1nOnvb47Wy5Kn1x+xP+0pNZX+DPOZlPnlaQAGrhzvSxgYXwYXQJHZKOLnKoSZbFsyfhrpct3JHF7pGYoORJ4KbJBMTC7IPdm7dToy85rsFGlPgQHPuhhYUbdFG7Nbs8iYt5vEof3an/Fm/uNYC0Yr6cNPse4=
