/*!
 * @imqueue/cli catalog: fleet analysis tests
 *
 * I'm Queue Software Project
 * Copyright (C) 2026  imqueue.com <support@imqueue.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * If you want to use this code in a closed source (commercial) project, you can
 * purchase a proprietary commercial license. Please contact us at
 * <support@imqueue.com> to get commercial licensing options.
 */
import assert from 'node:assert/strict';
import { after, before, describe, it } from 'node:test';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { tmpdir } from 'os';

// IMQ_CLI_HOME reroutes every path the CLI writes, the analysis cache included,
// so it has to be set BEFORE the modules under test resolve their constants.
const SANDBOX = mkdtempSync(join(tmpdir(), 'imq-fleet-home-'));

process.env.IMQ_CLI_HOME = SANDBOX;

const {
    analyseFleet,
    fleetCachePath,
    fleetDefaults,
    fleetNote,
    fleetNotes,
    fleetProposal,
    recordFleetChoices,
} = await import('../../../src/catalog/fleet.js');

/** The ORM view of an analysis, which most of these assertions are about. */
const orm = (a: any) => a.groups.orm;
const tracing = (a: any) => a.groups.tracing;

/** Gives a service a git remote, the only place a VCS host shows up. */
function remote(root: string, name: string, url: string): void {
    mkdirSync(join(root, name, '.git'), { recursive: true });
    writeFileSync(
        join(root, name, '.git', 'config'),
        `[remote "origin"]\n\turl = ${url}\n`,
    );
}

/** Gives a service a CI config, the only place a CI provider shows up. */
function ciConfig(root: string, name: string, file: string): void {
    const at = join(root, name, file);

    mkdirSync(dirname(at), { recursive: true });
    writeFileSync(at, '# generated by a test\n');
}

/** Writes a service directory with the given dependencies. */
function service(root: string, name: string, deps: string[]): void {
    mkdirSync(join(root, name), { recursive: true });
    writeFileSync(
        join(root, name, 'package.json'),
        JSON.stringify({
            name,
            dependencies: Object.fromEntries(deps.map(d => [d, '*'])),
        }),
    );
}

const RPC = '@imqueue/rpc';
const OTEL = '@imqueue/opentelemetry-instrumentation-imqueue';
const DD = '@imqueue/dd-trace';
const SEQ = '@imqueue/sequelize';
const PRISMA = '@imqueue/pg-prisma';

describe('analyseFleet()', () => {
    const fleets: string[] = [];

    function fleet(): string {
        const dir = mkdtempSync(join(tmpdir(), 'imq-fleet-'));

        fleets.push(dir);

        return dir;
    }

    before(() => rmSync(fleetCachePath(), { force: true }));
    after(() => {
        for (const dir of fleets) {
            rmSync(dir, { recursive: true, force: true });
        }
    });

    it('reads a Sequelize fleet as sequelize', () => {
        const root = fleet();

        service(root, 'auth', [RPC, SEQ]);
        service(root, 'billing', [RPC, SEQ]);
        service(root, 'gateway', [RPC]);

        const analysis = analyseFleet(root);

        assert.equal(orm(analysis).propose, 'sequelize');
        assert.equal(orm(analysis).counts.sequelize, 2);
        assert.equal(analysis.services, 3);
        assert.equal(orm(analysis).source, 'scan');
        assert.deepEqual(fleetDefaults(analysis), ['sequelize']);
        assert.match(fleetNotes(analysis).orm, /Preselected sequelize/);
        // the whole point of preselecting sequelize is not to silence the
        // alternative
        assert.match(
            fleetNotes(analysis).orm,
            /pg-prisma is worth considering/,
        );
    });

    it('reads a Prisma fleet as pg-prisma', () => {
        const root = fleet();

        service(root, 'lead', [RPC, PRISMA]);

        const analysis = analyseFleet(root);

        assert.equal(orm(analysis).propose, 'pg-prisma');
        assert.deepEqual(fleetDefaults(analysis), ['pg-prisma']);
        assert.match(fleetNotes(analysis).orm, /1 service in this fleet/);
    });

    it('recommends pg-prisma for a mixed fleet', () => {
        const root = fleet();

        service(root, 'old', [RPC, SEQ]);
        service(root, 'new', [RPC, PRISMA]);

        const analysis = analyseFleet(root);

        assert.equal(orm(analysis).propose, 'pg-prisma');
        assert.deepEqual(fleetDefaults(analysis), ['pg-prisma']);
        assert.match(fleetNotes(analysis).orm, /uses more than one ORM/);
    });

    it('preselects nothing when no service uses an ORM', () => {
        const root = fleet();

        service(root, 'gateway', [RPC]);

        const analysis = analyseFleet(root);

        assert.equal(orm(analysis).propose, null);
        // Guessing an ORM here would put a database in front of someone who
        // never asked for one.
        assert.deepEqual(fleetDefaults(analysis), []);
        assert.equal(fleetNotes(analysis).orm, undefined);
    });

    it('ignores directories that are not @imqueue services', () => {
        const root = fleet();

        service(root, 'docs', [SEQ]); // no @imqueue/rpc
        mkdirSync(join(root, 'node_modules'), { recursive: true });

        assert.equal(analyseFleet(root).services, 0);
    });

    it('answers from cache on the second call', () => {
        const root = fleet();

        service(root, 'auth', [RPC, SEQ]);

        assert.equal(orm(analyseFleet(root)).source, 'scan');
        assert.equal(orm(analyseFleet(root)).source, 'cache');
    });

    it('rescans when the fleet gains a directory', () => {
        const root = fleet();

        service(root, 'auth', [RPC, SEQ]);
        assert.equal(orm(analyseFleet(root)).propose, 'sequelize');

        service(root, 'lead', [RPC, PRISMA]);

        // A changed directory listing is one readdir to detect, which is what
        // keeps the cache from going stale behind a new service.
        const again = orm(analyseFleet(root));

        assert.equal(again.source, 'scan');
        assert.equal(again.propose, 'pg-prisma');
    });
});

describe('recordFleetChoices()', () => {
    const fleets: string[] = [];

    function fleet(): string {
        const dir = mkdtempSync(join(tmpdir(), 'imq-fleet-'));

        fleets.push(dir);

        return dir;
    }

    after(() => {
        for (const dir of fleets) {
            rmSync(dir, { recursive: true, force: true });
        }
    });

    it('remembers a choice that contradicts the scan', () => {
        const root = fleet();

        service(root, 'auth', [RPC, SEQ]);
        assert.equal(orm(analyseFleet(root)).propose, 'sequelize');

        recordFleetChoices(root, ['pg-prisma']);

        const after = analyseFleet(root);

        assert.equal(orm(after).propose, 'pg-prisma');
        assert.equal(orm(after).source, 'override');
        assert.deepEqual(fleetDefaults(after), ['pg-prisma']);
        assert.match(fleetNotes(after).orm, /your earlier choice here/);
    });

    it('keeps the override when the fleet changes but still disagrees', () => {
        const root = fleet();

        service(root, 'auth', [RPC, SEQ]);
        analyseFleet(root);
        recordFleetChoices(root, ['pg-prisma']);

        service(root, 'audit', [RPC, SEQ]);

        // Intent outlives a rescan: the user said pg-prisma for this path.
        assert.equal(orm(analyseFleet(root)).propose, 'pg-prisma');
    });

    it('drops the override once the fleet agrees with it', () => {
        const root = fleet();

        service(root, 'auth', [RPC, SEQ]);
        analyseFleet(root);
        recordFleetChoices(root, ['pg-prisma']);

        // fleet migrated: nothing left to override, so a later change is not
        // masked by a stale intent
        rmSync(join(root, 'auth'), { recursive: true, force: true });
        service(root, 'lead', [RPC, PRISMA]);

        const after = orm(analyseFleet(root));

        assert.equal(after.propose, 'pg-prisma');
        assert.equal(after.source, 'scan');
    });

    it('does not treat agreement, or no ORM, as an instruction', () => {
        const root = fleet();

        service(root, 'auth', [RPC, SEQ]);
        analyseFleet(root);

        recordFleetChoices(root, ['sequelize']);
        assert.equal(orm(analyseFleet(root)).source, 'cache');

        recordFleetChoices(root, ['pg-cache']);
        assert.equal(orm(analyseFleet(root)).source, 'cache');
    });
});

describe('analyseFleet() tracing', () => {
    const fleets: string[] = [];

    function fleet(): string {
        const dir = mkdtempSync(join(tmpdir(), 'imq-fleet-'));

        fleets.push(dir);

        return dir;
    }

    after(() => {
        for (const dir of fleets) {
            rmSync(dir, { recursive: true, force: true });
        }
    });

    it('proposes the tracing backend the fleet already uses', () => {
        const root = fleet();

        service(root, 'auth', [RPC, DD]);
        service(root, 'billing', [RPC, DD]);

        const analysis = analyseFleet(root);

        assert.equal(tracing(analysis).propose, 'dd-trace');
        assert.deepEqual(fleetDefaults(analysis), ['dd-trace']);
        assert.match(fleetNotes(analysis).tracing, /Preselected dd-trace/);
    });

    it('follows the majority when a fleet uses both', () => {
        const root = fleet();

        service(root, 'a', [RPC, OTEL]);
        service(root, 'b', [RPC, OTEL]);
        service(root, 'c', [RPC, DD]);

        const analysis = analyseFleet(root);

        // Neither backend is "recommended" — it is a vendor choice — so the
        // fleet's own majority is the only honest basis.
        assert.equal(tracing(analysis).propose, 'opentelemetry');
        assert.match(
            fleetNotes(analysis).tracing,
            /uses more than one tracing \(2 on opentelemetry, 1 on dd-trace\)/,
        );
        // and no "worth considering" nudge, since the project prefers neither
        assert.equal(
            /worth considering/.test(fleetNotes(analysis).tracing),
            false,
        );
    });

    it('proposes nothing for an evenly split fleet, and says so', () => {
        const root = fleet();

        service(root, 'a', [RPC, OTEL]);
        service(root, 'b', [RPC, DD]);

        const analysis = analyseFleet(root);

        assert.equal(tracing(analysis).propose, null);
        assert.deepEqual(fleetDefaults(analysis), []);
        assert.match(fleetNotes(analysis).tracing, /split evenly/);
    });

    it('proposes nothing when the fleet is not traced', () => {
        const root = fleet();

        service(root, 'auth', [RPC, SEQ]);

        const analysis = analyseFleet(root);

        assert.equal(tracing(analysis).propose, null);
        assert.equal(fleetNotes(analysis).tracing, undefined);
        // the ORM half of the same scan still answers
        assert.deepEqual(fleetDefaults(analysis), ['sequelize']);
    });

    it('remembers a tracing choice that contradicts the scan', () => {
        const root = fleet();

        service(root, 'auth', [RPC, DD]);
        analyseFleet(root);

        recordFleetChoices(root, ['opentelemetry']);

        const after = analyseFleet(root);

        assert.equal(tracing(after).propose, 'opentelemetry');
        assert.equal(tracing(after).source, 'override');
    });

    it('records overrides for both groups from one selection', () => {
        const root = fleet();

        service(root, 'auth', [RPC, SEQ, DD]);
        analyseFleet(root);

        recordFleetChoices(root, ['pg-prisma', 'opentelemetry']);

        const after = analyseFleet(root);

        assert.equal(orm(after).propose, 'pg-prisma');
        assert.equal(tracing(after).propose, 'opentelemetry');
        assert.deepEqual(fleetDefaults(after).sort(), [
            'opentelemetry',
            'pg-prisma',
        ]);
    });
});

describe('analyseFleet() vcs and ci', () => {
    const fleets: string[] = [];

    function fleet(): string {
        const dir = mkdtempSync(join(tmpdir(), 'imq-fleet-'));

        fleets.push(dir);

        return dir;
    }

    after(() => {
        for (const dir of fleets) {
            rmSync(dir, { recursive: true, force: true });
        }
    });

    it('reads the VCS host out of the git remotes', () => {
        const root = fleet();

        service(root, 'auth', [RPC]);
        remote(root, 'auth', 'git@gitlab.example.com:acme/auth.git');
        service(root, 'billing', [RPC]);
        remote(root, 'billing', 'https://gitlab.example.com/acme/billing.git');

        const analysis = analyseFleet(root);

        // Matched on host, not domain: a self-hosted GitLab is still GitLab.
        assert.equal(fleetProposal(analysis, 'vcs'), 'gitlab');
        assert.match(fleetNote(analysis, 'vcs'), /Preselected gitlab/);
        // and never leaks into the catalog, which would reject it as a package
        assert.deepEqual(fleetDefaults(analysis), []);
    });

    it('reads the CI provider out of its config files', () => {
        const root = fleet();

        service(root, 'auth', [RPC]);
        ciConfig(root, 'auth', '.circleci/config.yml');
        service(root, 'billing', [RPC]);
        ciConfig(root, 'billing', '.circleci/config.yml');

        assert.equal(fleetProposal(analyseFleet(root), 'ci'), 'circleci');
    });

    it('recognises a github-actions workflow directory', () => {
        const root = fleet();

        service(root, 'auth', [RPC]);
        ciConfig(root, 'auth', '.github/workflows/build.yml');
        remote(root, 'auth', 'git@github.com:acme/auth.git');

        const analysis = analyseFleet(root);

        assert.equal(fleetProposal(analysis, 'ci'), 'github-actions');
        assert.equal(fleetProposal(analysis, 'vcs'), 'github');
    });

    it('says nothing about a host it cannot recognise', () => {
        const root = fleet();

        service(root, 'auth', [RPC]);
        // GitHub Enterprise on a custom domain leaves no evidence, and no
        // evidence is reported as no evidence rather than guessed at
        remote(root, 'auth', 'git@git.acme.internal:acme/auth.git');

        const analysis = analyseFleet(root);

        assert.equal(fleetProposal(analysis, 'vcs'), null);
        assert.equal(fleetNote(analysis, 'vcs'), '');
    });

    it('follows the majority host, and calls a tie a tie', () => {
        const split = fleet();

        service(split, 'a', [RPC]);
        remote(split, 'a', 'git@github.com:acme/a.git');
        service(split, 'b', [RPC]);
        remote(split, 'b', 'git@gitlab.com:acme/b.git');

        assert.equal(fleetProposal(analyseFleet(split), 'vcs'), null);
        assert.match(fleetNote(analyseFleet(split), 'vcs'), /split evenly/);

        const most = fleet();

        service(most, 'a', [RPC]);
        remote(most, 'a', 'git@github.com:acme/a.git');
        service(most, 'b', [RPC]);
        remote(most, 'b', 'git@github.com:acme/b.git');
        service(most, 'c', [RPC]);
        remote(most, 'c', 'git@gitlab.com:acme/c.git');

        assert.equal(fleetProposal(analyseFleet(most), 'vcs'), 'github');
    });

    it('remembers a VCS or CI choice that contradicts the scan', () => {
        const root = fleet();

        service(root, 'auth', [RPC]);
        remote(root, 'auth', 'git@github.com:acme/auth.git');
        ciConfig(root, 'auth', '.github/workflows/build.yml');
        analyseFleet(root);

        recordFleetChoices(root, ['gitlab', 'circleci']);

        const after = analyseFleet(root);

        assert.equal(fleetProposal(after, 'vcs'), 'gitlab');
        assert.equal(fleetProposal(after, 'ci'), 'circleci');
        assert.match(fleetNote(after, 'vcs'), /your earlier choice here/);
    });
});
